### ISSUE TITLE
Is this for the Testing Guide?

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-project-web-security-testing-guide#1]
@hblankenship @mikemccamon Is this repo meant to be for the Testing Guide project?

**Comment by kingthorin** [comment]
Nope that’s fine, just wanted to be clear amongst various stakeholders.

**Comment by kingthorin** [comment]
Hi @hblankenship I've just submitted the form to be added as admin for this repo. If it helps you can see on the project repo: https://github.com/OWASP/OWASP-Testing-Guide-v5/settings/collaboration that Matt, Elie, and I are admin there.

Thanks for your continued work on this!

**Comment by hblankenship** [comment]
I've added you and Matt to that repo.  Are you officially a leader on that
project?  If so, you are not listed in our records as such.

Cheers,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by kingthorin** [comment]
@hblankenship you should have received a leadership update sometime in the last few weeks from @MatOwasp or Andrew Muller.

**Comment by MatMinded** [comment]
Hi @hblankenship , yes @kingthorin and Elie Saad are the two new co-leaders of the new OWASP Testing Guide project. Andrew Muller is not more in charge.
Thanks,
Mat

**Comment by victoriadrake** [comment]
@kingthorin Is this resolved?

**Comment by kingthorin** [comment]
Excellent question, I think it is. But @hblankenship would know best if the org has updated its records, etc.

**Comment by hblankenship** [comment]
Yes.
